import os
from os import *
TitleZero=('title EXE.PY')
os.system(TitleZero)
os.system("color 01")
os.system("mode 66,11")
os.system("cd C:\\Python27\\")
cls = 'cls'
os.system(cls)
print("By Kia7L: PY to EXE")
print("Type Name Only")
python27path=("C:\Python27\Scripts\pyinstaller.exe")
a=(raw_input("ICON?Name! : "))
b=(raw_input(".PY?Name! : "))
c=(' -F -i .\\'+a)
d=('.ico ')
e=('.\\'+b)
f=('.py')
os.system(python27path+c+d+e+f)
input()
